---
all:
  children:

    APIC:
      hosts:
        #
        #  This APIC is within the WWT Advanced Technology Center
        #
        aci-demo.sandbox.wwtatc.local:
          apic_hostname: aci-demo.sandbox.wwtatc.local
          apic_username: admin
          apic_use_proxy: no
          apic_validate_certs: no
          apic_password: foo!bar
        #
        # This APIC is in the DevNet Sandbox 
        #
        sandboxapicdc.cisco.com:
          apic_hostname: sandboxapicdc.cisco.com
          apic_username: admin
          apic_use_proxy: no
          apic_validate_certs: no
          apic_password: ciscopsdt

    MinIO:
      hosts:
        s3.amazonaws.com: {}
