#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology, LLC.
#      All rights reserved.
#
#      author: joel.king@wwt.com GitHub/GitLab @joelwking
#
#      description: 
#
#        This playbook ....
#
#      usage:
#
#        ./UPDATEME.yml -v
#
#
- name: Demo for the Cisco Data Center Community of Interest
  hosts:  localhost
  connection: local
  gather_facts: no

  vars:

    provider:
      hostname: 'rocket.sandbox.wwtatc.local'
      database: ACI
      collection: dccoi
    queries:
       - _id: 5d07e307e349b507d8d41d57


    acl_action: {"ALLOW": "permit", "DROP": "deny"}        # translator for action verbs

  tasks:      
    - name: debug
      debug:
        msg: '{{ acl_action }}'
