#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2020 World Wide Technology, LLC.
#      All rights reserved.
#
#      author: joel.king@wwt.com GitHub/GitLab @joelwking
#
#      description: 
#
#        This playbook manages Tenants, VRFs and fabric policies to demonstrate the Ansible ACI contenct collection and WWT developed roles.
#
#      usage:
#
#        ./sample.yml -v -i inventory.yml --e 'bootstrap=sample123 apic_hostname=sandboxapicdc.cisco.com apic_password=foo!bar'
#
#        sample123.yml must be in the '{{ playbook_dir }}/files/' directory
#
#      Requirements:
#        If not installed, download csv_to_facts.py and mongodb_iq.py to ./library/
#        wget https://raw.githubusercontent.com/joelwking/ansible-nxapi/master/csv_to_facts.py 
#
#
- name: Demo using roles rather than calling modules directly from a playbook
  hosts:  '{{ apic_hostname }}'
  connection: local
  gather_facts: no

  collections:
    - cisco.aci
    - joelwking.mongodb

  vars:

    apic:                                # ansible-aci-credentials needs a username and password
      username: admin                    # typically you would define these variables in passwords.yml
      password: '{{ apic_password }}'    # and ansible-vault the file

    bootstrap: sample123.yml             # ansible-aci-include-data needs a bootstrap filename

  roles:
    - ansible-aci-credentials
    - ansible-aci-include-data    

  tasks:
    - name: Tenant Policy debugs
      block:
        - debug:
            msg: '{{ item }}'
          loop: '{{ spreadsheet }}'

        - debug:
            msg: '{{ item.tenant }} {{ item.description }} {{ item.state }}'
          loop: '{{ FVTENANT }}'

    - name: Manage Tenants
      include_role:
        name: ansible-aci-tenant
      vars:
        desired_state: '{{ item.state }}'
        fvTenant:
          name: '{{ item.tenant }}'
          descr: '{{ item.description }} | configured using bootstrap file: {{ bootstrap }}'
      loop: '{{ FVTENANT }}'

    - name: Manage VRFs for the specified Tenant
      include_role:
        name: ansible-aci-vrf
      vars:
        desired_state: '{{ item.vrf_state }}'
        fvTenant:
          name: '{{ item.tenant }}'
        fvCtx:
          name: '{{ item.vrf }}'
          descr: '{{ item.description }} {{ item.comments }}'
          pcEnfPref: '{{ item.pcEnfPref }}'
          pcEnfDir: '{{ item.pcEnfDir }}'
      loop: '{{ spreadsheet }}'

        #
        #  ... and so on ...
        #

    - name: Delete certificate and key file
      include_role:
        name: ansible-aci-credentials
        tasks_from: delete
