#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2019 World Wide Technology, LLC.
#      All rights reserved.
#
#      author: joel.king@wwt.com GitHub/GitLab @joelwking
#
#      description: 
#
#        This playbook ....
#
#      usage:
#
#        ./UPDATEME.yml -v   -e 'apic_password=foo!bar'
#
#
- name: Demo for the Cisco Data Center Community of Interest
  hosts:  sandboxapicdc.cisco.com
  connection: local
  gather_facts: no

  vars:
    # We prepare an aci_login anchor for convenience
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'
      timeout: '{{ apic_timeout }}'
      use_ssl: '{{ apic_use_ssl }}'

    desired_state: present

  tasks:      
    - name: Tenant (fvTenant)
      cisco.aci_tenant:
        <<: *aci_login
        #
        state: '{{ desired_state }}'
        #
        tenant: '{{ fvTenant.name }}'
        description: '{{ fvTenant.descr }}'